--- !ruby/object:VR_ENV
settings_file_version: 1
width: 1183
height: 623
panel_pos: 360
run_command_line: ruby main.rb
open_files:
- /home/hiroshi/Dropbox/Programming/music-manager/main.rb
- /home/hiroshi/Dropbox/Programming/music-manager/bin/MyClass.rb
open_folders:
- /home/hiroshi/Dropbox/Programming/music-manager
- /home/hiroshi/Dropbox/Programming/music-manager/bin
- /home/hiroshi/Dropbox/Programming/music-manager/bin/glade
current_file: /home/hiroshi/Dropbox/Programming/music-manager/bin/MyClass.rb
rdoc_command_line: rdoc -x README
